### ISSUE TITLE
Main Wiki: Add Comparison info

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_threefold#13]
There are a number of projects on the market that come across as similar, offering decentralized storage or what might be promoted as a decentralized cloud – but we believe ThreeFold is operating in a unique territory. Some things that make us different:

1. ThreeFold is not just decentralized, it’s fully peer-to-peer. This goes beyond decentralization, it enables everyone to become the centre of their own digital life.

Learn more about peer-to-peer here: https://threefold.io/blog/post/what_is_peer_to_peer/.

2. ThreeFold offers a full scope peer-to-peer cloud – storage, compute, and network. That’s a first in the decentralization space. There are other players out there offering a piece of the puzzle, but nobody truly offering the entire package – besides us. 

Also, ThreeFold integrated IT standards such as Kubernetes and Docker to our Compute solution, enabling a smooth transition for developers from traditional clouds to ThreeFold.

Learn more about P2P Cloud here: https://threefold.io/info/cloud#/cloud__readme – and about the solutions stack: https://threefold.io/info/cloud#/cloud__usp_compatible.

3. Zero-OS a lightweight, stateless, peer-to-peer operating system, takes care of all cloud requirements together. Combined with ThreeFold’s Quantum Safe Filesystem, which uses a dispersed storage algorithm, game-changing security and efficiency is achieved.

The dispersed algorithm breaks data into shards and stores them on different nodes. Only the data owner, via their private key, can retrieve and re-create the information. This removes the necessity to duplicate data for security

Learn more about Zero-OS here: https://wiki.threefold.io/#/threefold__grid_architecture?id=zero-os.

4. Data is stored in Zero-Databases (ZDBs). ZDBs manage the disks in a way it cannot be stretched out, and communicate to the network. This is a super simple solution to receive data and store it in an always append way on the disk. Therefore, data is not stored in a sequential way but is continuously updated. 

Learn more about Zero-DBs here: https://threefold.io/info/threefold#/cloud__evdc_storage?id=manage-storage-nodes

5. In most distributed systems, data is stored multiple times to guarantee redundancy. This leads to a lot of unnecessary overhead and is also not the most secure mechanism. Threefold uses a dispersed storage algorithm to store the workloads on the ThreeFold Grid. 

The dispersed storage algorithm takes the object, describes parts of that object, creates equations for each part, and stores these equations on different nodes. Think of it like a puzzle, where equations leading to different parts of the puzzle are stored in different locations.

Learn more about the dispersed storage algorithm here: https://info.threefold.io/#/threefold__part5_ultra_efficient_storage?id=the-space-algorithm-of-storage

6. The blockchain database (BCDB) acts as a registry for the workloads on the Threefold Grid. Workloads can only be accessed and managed with the private key of the data owner. The BCDB can prove to any party that their workloads are executed exactly as intended and that their data is untouched.

Learn more about the blockchain database here: https://threefold.io/info/threefold#/threefold__part6_bcdb_powerful_database?id=blockchain-database-bcdb

Learn more about the transaction blockchain here: https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1?filter=markets.

7. Autonomous IT automates the deployment process and all other user commands on the ThreeFold Grid. Autonomous IT ensures the smart contracts are stored in the blockchain database and that workloads are executed as defined by the user on the network with 3Bot. 

Learn more about Autonomous IT here: https://wiki.threefold.io/#/threefold__grid_intro?id=what-is-autonomous-technology.

8. 3Bot is the virtual system administrator technology on the ThreeFold Grid. It is the unique identity someone needs on the ThreeFold Grid. It executes the commands and functions of the user via Autonomous IT to reserve, use and run the compute, storage and network on the Threefold Grid. 

It comes with a private key that enables access and management on ThreeFold's BCDB and to transact on the Stellar blockchain - where TFT, the official currency of the ThreeFold Grid, currently lives.

Learn more about 3Bot here: https://threefold.io/info/threefold#/threefold__part6_bcdb_powerful_database?id=blockchain-database-bcdb.

Some helpful links:

https://wiki.threefold.io/#/threefold__grid_compare
https://compare.threefold.me (take note of the disclaimer on top)

**Comment by Sacha96** [comment]
ThreeFold: A different approach to Blockchain

ThreeFold had no ICO nor IEO. It pre-farmed it’s tokens. 

ThreeFold didn’t have any ICO or IEO. ICOs and IEOs are fundraising schemes for blockchains to sell tokens to investors either directly (ICO) or through regulated exchanges (IEO). Instead, ThreeFold pre-farmed (ThreeFold’s sustainable alternative to mining) its tokens prior to going to the market. 

This allowed ThreeFold to incentivise its early contributors, while also securing the ongoing development of the project until the launch of the Threefold Grid 2.0 in April 2020. Pre-mining is also an organic approach to the market, in line with ThreeFold’s values and vision of delivering products over using hype.

Product over Hype.

In some cases ICOs and IEOs were surrounded with hype. It is always very hard to judge the ability of a project to deliver it’s promises over a white paper.

Threefold therefore didn’ do an ICO or IEO. Instead of fundraising with a white paper, the technological development remained the primary focus. For 4 years, ThreeFold developed the whole technology stack, starting with an operating-system built from scratch to the autonomous smart contract and virtual system administrator technology that enables a fully autonomous Cloud. 

In 2020, ThreeFold held its Token public launch on Liquid Exchange. At that time, the ThreeFold Grid was already live in it’s 2nd version.

Today, you can go through the whole Threefold Universe and find ready-to-use products. You can participate in growing the world’s most advanced peer-to-peer Internet infrastructure, or use the peer-to-peer compute and storage capacity available on the P2P Cloud. 

ThreeFold is much more than a blockchain. 

Threefold is not actually a blockchain project, rather it uses blockchain technology by combining it with other cutting-edge solutions. It is way more that just a blockchain alternative to a public cloud. ThreeFold started everything from scratch; built a super-lightweight and shell-less operating system, and a fully autonomous (self-driving and self-healing) architecture to enable a true peer-to-peer infrastructure with zero intermediaries that leads to high efficiency and minimum complexity. 

The blockchain database (BCDB) acts a registry for the workloads on the Threefold Grid. Workloads can only be accessed and managed with the private key of the data owner. The BCDB can prove to any party that their workloads are executed exactly as intended and that their data is untouched.

In most distributed systems, data is stored multiple times to guarantee redundancy. This leads to a lot of unnecessary overhead and is also not the most secure mechanism. Threefold uses a dispersed storage algorithm to store the workloads on the ThreeFold Grid. The dispersed storage algorithm breaks data into shards and stores them on different nodes. This enables two things – first, performance efficiency (no need for consensus to run compute and storage) and second, energy efficiency (as there’s no more need for data duplication).

**Comment by Sacha96** [comment]
Title: How is ThreeFold Unique?

Questions: link to Why or Grid?
- Mention in Why and have in Grid?
- Link from main.io?

**Comment by Sacha96** [comment]
Maybe this should go in cloud wiki instead of main wiki @gmachtel @weynandkuijpers what do you think?

**Comment by gmachtel** [comment]
to me this is about more than just the usage side of the story. Cloud wiki is aimed for consumers. To me, main wiki is a more obvious place.

**Comment by Sacha96** [comment]
This will now change to the Internet 4 primitives for compute storage and network
